# planner_server:
#   ros__parameters:
#     expected_planner_frequency: 2.0
#     use_sim_time: False
#     planner_plugins: ["GridBased"]
#     GridBased:
#       plugin: "nav2_navfn_planner/NavfnPlanner"
#       tolerance: 0.5
#       use_astar: false
#       allow_unknown: true

# global_costmap:
#   global_costmap:
#     ros__parameters:
#       update_frequency: 1.0
#       publish_frequency: 1.0
#       global_frame: map
#       robot_base_frame: robot_base_footprint
#       use_sim_time: False
#       robot_radius: 0.25
#       resolution: 0.05
#       track_unknown_space: true
#       plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
#       filters: ["keepout_filter", "inflation_layer"]
#       static_layer:
#         plugin: "nav2_costmap_2d::StaticLayer"
#         map_subscribe_transient_local: True
#       obstacle_layer:
#         plugin: "nav2_costmap_2d::ObstacleLayer"
#         enabled: True
#         observation_sources: scan
#         scan:
#           topic: /scan
#           max_obstacle_height: 2.0
#           clearing: True
#           marking: True
#           data_type: "LaserScan"
#           raytrace_max_range: 3.0
#           raytrace_min_range: 0.0
#           obstacle_max_range: 2.5
#           obstacle_min_range: 0.0
#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         cost_scaling_factor: 6.0
#         inflation_radius: 0.45
#       keepout_filter:
#         plugin: "nav2_costmap_2d::KeepoutFilter"
#         enabled: True
#         filter_info_topic: "/costmap_filter_info"
#       always_send_full_costmap: True


planner_server:
  ros__parameters:
    # usar el timepo de simulación
    use_sim_time: False
    # Frecuencia con la que el planificador  genere un plan
    expected_planner_frequency: 2.0
    # Plugin a uTilizar
    planner_plugins: ["GridBased"]
    #~~~~~~~~~~~~~Configuración de plugin~~~~~~~~~~~~
    GridBased:
      # Tipo de plugin
      plugin: "nav2_navfn_planner/NavfnPlanner"
      # Tolerancia de la meta
      tolerance: 0.15
      #tolerance: 0.30
      # usar el algoritmo A*
      use_astar: false
      # Permitir que la ruta se genera en espacios no explorados del map
      allow_unknown: true


global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: robot_base_footprint
      # Radio del robot a utilizar, si no se proporcionan las coordenadas de la huella.
      robot_radius: 0.25
      resolution: 0.05
      track_unknown_space: true
      transform_tolerance: 0.5
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      filters: ["keepout_filter"]
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
      #~~~~~~~~~~~~~~~~~~Static layer~~~~~~~~~~~~~~~~~~~+
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        transform_tolerance: 0.5
      #~~~~~~~~~~~~~~~~~~~Inflation layer~~~~~~~~~~~~~~~~~~~+
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 6.0
        inflation_radius: 0.5
      #~~~~~~~~~~~~~~~~~~~Obstacle layer config~~~~~~~~~~~~~~~~~~~+
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        #habilitar capa de obstáculos
        enabled: True
        #Despeje las celdas ocupadas bajo la huella del robot.
        footprint_clearing_enabled: True
        #fuente de observación
        observation_sources: scan
        scan:
          topic: /scan
          # Parámetro para cámaras 3d
          max_obstacle_height: 2.0
          # Si la fuente debe marcarse en el mapa de costes.
          # Si la fuente debe raytrace claro en costmap.
          clearing: True
          marking: True
          # Tipo de dato
          data_type: "LaserScan"
          # Alcance máximo del trazado de rayos para eliminar obstáculos del mapa de costes.
          raytrace_max_range: 7.0
          # Alcance mínimo del trazado de rayos para eliminar obstáculos del mapa de costes.
          raytrace_min_range: 0.0
          # Alcance máximo para marcar obstáculos en el mapa de costes.
          obstacle_max_range: 2.5
          # Alcance mínimo para marcar obstáculos en el mapa de costes
          obstacle_min_range: 0.0
      # Si se envía el mapa de costes completo en cada actualización, en lugar de las actualizaciones.
      always_send_full_costmap: True